/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expenditure {
  'date' : string,
  'description' : string,
  'category' : ExpenditureCategory,
  'amount' : bigint,
}
export type ExpenditureCategory = { 'other' : null } |
  { 'supplies' : null } |
  { 'labour' : null } |
  { 'rent' : null } |
  { 'transport' : null } |
  { 'utilities' : null };
export interface InventoryItem {
  'plantName' : string,
  'unit' : string,
  'sellingPrice' : bigint,
  'category' : string,
  'currentStock' : bigint,
  'costPrice' : bigint,
}
export interface Invoice {
  'tax' : bigint,
  'customerName' : string,
  'lineItems' : Array<SaleItem>,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : string,
  'date' : string,
  'grandTotal' : bigint,
  'invoiceNumber' : bigint,
  'discount' : bigint,
  'subtotal' : bigint,
}
export type MovementReason = { 'adjustment' : null } |
  { 'loss' : null } |
  { 'sale' : null } |
  { 'purchase' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'card' : null } |
  { 'cash' : null };
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null };
export interface PriorityRequest {
  'id' : bigint,
  'customerName' : string,
  'status' : PriorityRequestStatus,
  'plantName' : string,
  'customerPhone' : string,
  'plantVariety' : string,
  'deliveryDate' : [] | [string],
  'notes' : [] | [string],
  'quantity' : bigint,
  'requestDate' : string,
  'wantedDate' : string,
}
export interface PriorityRequestCreate {
  'customerName' : string,
  'status' : PriorityRequestStatus,
  'plantName' : string,
  'customerPhone' : string,
  'plantVariety' : string,
  'deliveryDate' : [] | [string],
  'notes' : [] | [string],
  'quantity' : bigint,
  'requestDate' : string,
  'wantedDate' : string,
}
export type PriorityRequestStatus = { 'pending' : null } |
  { 'fulfilled' : null };
export interface SaleItem {
  'plantName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface SalesRecord {
  'customerName' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'customerPhoto' : [] | [string],
  'date' : string,
  'customerMobile' : [] | [string],
  'totalAmount' : bigint,
  'items' : Array<SaleItem>,
  'billingNumber' : string,
}
export interface StockMovement {
  'date' : string,
  'notes' : string,
  'quantity' : bigint,
  'reason' : MovementReason,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpenditure' : ActorMethod<[Expenditure], undefined>,
  'addInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'addPriorityRequest' : ActorMethod<[PriorityRequestCreate], bigint>,
  'addSale' : ActorMethod<[SalesRecord], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvoice' : ActorMethod<[Invoice], bigint>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deleteSale' : ActorMethod<[string], undefined>,
  'getAllExpenditures' : ActorMethod<[], Array<Expenditure>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInventory' : ActorMethod<[], Array<InventoryItem>>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getMyRole' : ActorMethod<[], UserRole>,
  'getPriorityRequests' : ActorMethod<[], Array<PriorityRequest>>,
  'getSales' : ActorMethod<[], Array<SalesRecord>>,
  'getSalesByPlant' : ActorMethod<[string, string, string], [bigint, bigint]>,
  'getStockMovements' : ActorMethod<[string], Array<StockMovement>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordStockMovement' : ActorMethod<[string, StockMovement], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventoryItem' : ActorMethod<[string, InventoryItem], undefined>,
  'updatePriorityRequestStatus' : ActorMethod<
    [bigint, PriorityRequestStatus, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];