/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpenditureCategory = IDL.Variant({
  'other' : IDL.Null,
  'supplies' : IDL.Null,
  'labour' : IDL.Null,
  'rent' : IDL.Null,
  'transport' : IDL.Null,
  'utilities' : IDL.Null,
});
export const Expenditure = IDL.Record({
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : ExpenditureCategory,
  'amount' : IDL.Nat,
});
export const InventoryItem = IDL.Record({
  'plantName' : IDL.Text,
  'unit' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'category' : IDL.Text,
  'currentStock' : IDL.Nat,
  'costPrice' : IDL.Nat,
});
export const PriorityRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
});
export const PriorityRequestCreate = IDL.Record({
  'customerName' : IDL.Text,
  'status' : PriorityRequestStatus,
  'plantName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'plantVariety' : IDL.Text,
  'deliveryDate' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'requestDate' : IDL.Text,
  'wantedDate' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const SaleItem = IDL.Record({
  'plantName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const SalesRecord = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'customerPhoto' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'customerMobile' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(SaleItem),
  'billingNumber' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const Invoice = IDL.Record({
  'tax' : IDL.Nat,
  'customerName' : IDL.Text,
  'lineItems' : IDL.Vec(SaleItem),
  'paymentStatus' : PaymentStatus,
  'customerPhone' : IDL.Text,
  'date' : IDL.Text,
  'grandTotal' : IDL.Nat,
  'invoiceNumber' : IDL.Nat,
  'discount' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const PriorityRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : PriorityRequestStatus,
  'plantName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'plantVariety' : IDL.Text,
  'deliveryDate' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'requestDate' : IDL.Text,
  'wantedDate' : IDL.Text,
});
export const MovementReason = IDL.Variant({
  'adjustment' : IDL.Null,
  'loss' : IDL.Null,
  'sale' : IDL.Null,
  'purchase' : IDL.Null,
});
export const StockMovement = IDL.Record({
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'reason' : MovementReason,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpenditure' : IDL.Func([Expenditure], [], []),
  'addInventoryItem' : IDL.Func([InventoryItem], [], []),
  'addPriorityRequest' : IDL.Func([PriorityRequestCreate], [IDL.Nat], []),
  'addSale' : IDL.Func([SalesRecord], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'deleteSale' : IDL.Func([IDL.Text], [], []),
  'getAllExpenditures' : IDL.Func([], [IDL.Vec(Expenditure)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getMyRole' : IDL.Func([], [UserRole], ['query']),
  'getPriorityRequests' : IDL.Func([], [IDL.Vec(PriorityRequest)], ['query']),
  'getSales' : IDL.Func([], [IDL.Vec(SalesRecord)], ['query']),
  'getSalesByPlant' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getStockMovements' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StockMovement)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordStockMovement' : IDL.Func([IDL.Text, StockMovement], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInventoryItem' : IDL.Func([IDL.Text, InventoryItem], [], []),
  'updatePriorityRequestStatus' : IDL.Func(
      [IDL.Nat, PriorityRequestStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpenditureCategory = IDL.Variant({
    'other' : IDL.Null,
    'supplies' : IDL.Null,
    'labour' : IDL.Null,
    'rent' : IDL.Null,
    'transport' : IDL.Null,
    'utilities' : IDL.Null,
  });
  const Expenditure = IDL.Record({
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : ExpenditureCategory,
    'amount' : IDL.Nat,
  });
  const InventoryItem = IDL.Record({
    'plantName' : IDL.Text,
    'unit' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'category' : IDL.Text,
    'currentStock' : IDL.Nat,
    'costPrice' : IDL.Nat,
  });
  const PriorityRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
  });
  const PriorityRequestCreate = IDL.Record({
    'customerName' : IDL.Text,
    'status' : PriorityRequestStatus,
    'plantName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'plantVariety' : IDL.Text,
    'deliveryDate' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'requestDate' : IDL.Text,
    'wantedDate' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
  });
  const SaleItem = IDL.Record({
    'plantName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const SalesRecord = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'customerPhoto' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'customerMobile' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(SaleItem),
    'billingNumber' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({ 'paid' : IDL.Null, 'unpaid' : IDL.Null });
  const Invoice = IDL.Record({
    'tax' : IDL.Nat,
    'customerName' : IDL.Text,
    'lineItems' : IDL.Vec(SaleItem),
    'paymentStatus' : PaymentStatus,
    'customerPhone' : IDL.Text,
    'date' : IDL.Text,
    'grandTotal' : IDL.Nat,
    'invoiceNumber' : IDL.Nat,
    'discount' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const PriorityRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : PriorityRequestStatus,
    'plantName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'plantVariety' : IDL.Text,
    'deliveryDate' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'requestDate' : IDL.Text,
    'wantedDate' : IDL.Text,
  });
  const MovementReason = IDL.Variant({
    'adjustment' : IDL.Null,
    'loss' : IDL.Null,
    'sale' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const StockMovement = IDL.Record({
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'reason' : MovementReason,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpenditure' : IDL.Func([Expenditure], [], []),
    'addInventoryItem' : IDL.Func([InventoryItem], [], []),
    'addPriorityRequest' : IDL.Func([PriorityRequestCreate], [IDL.Nat], []),
    'addSale' : IDL.Func([SalesRecord], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'deleteSale' : IDL.Func([IDL.Text], [], []),
    'getAllExpenditures' : IDL.Func([], [IDL.Vec(Expenditure)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getMyRole' : IDL.Func([], [UserRole], ['query']),
    'getPriorityRequests' : IDL.Func([], [IDL.Vec(PriorityRequest)], ['query']),
    'getSales' : IDL.Func([], [IDL.Vec(SalesRecord)], ['query']),
    'getSalesByPlant' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getStockMovements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StockMovement)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordStockMovement' : IDL.Func([IDL.Text, StockMovement], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInventoryItem' : IDL.Func([IDL.Text, InventoryItem], [], []),
    'updatePriorityRequestStatus' : IDL.Func(
        [IDL.Nat, PriorityRequestStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };