/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InventoryItem {
    stockQuantity: bigint;
    plantName: string;
    unit: string;
    sellingPrice: bigint;
    category: string;
    costPrice: bigint;
}
export interface Expenditure {
    date: string;
    description: string;
    category: ExpenditureCategory;
    amount: bigint;
}
export interface SalesRecord {
    customerName?: string;
    paymentMethod: PaymentMethod;
    customerPhoto?: string;
    date: string;
    customerMobile?: string;
    totalAmount: bigint;
    items: Array<SaleItem>;
}
export interface Invoice {
    tax: bigint;
    customerName: string;
    lineItems: Array<SaleItem>;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
}
export interface StockMovement {
    date: string;
    notes: string;
    quantity: bigint;
    reason: MovementReason;
}
export interface SaleItem {
    plantName: string;
    quantity: bigint;
    unitPrice: bigint;
}
export enum ExpenditureCategory {
    other = "other",
    supplies = "supplies",
    labour = "labour",
    rent = "rent",
    transport = "transport",
    utilities = "utilities"
}
export enum MovementReason {
    adjustment = "adjustment",
    loss = "loss",
    sale = "sale",
    purchase = "purchase"
}
export enum PaymentMethod {
    upi = "upi",
    card = "card",
    cash = "cash"
}
export enum PaymentStatus {
    paid = "paid",
    unpaid = "unpaid"
}
export interface backendInterface {
    addExpenditure(exp: Expenditure): Promise<void>;
    addInventoryItem(item: InventoryItem): Promise<void>;
    addSalesRecord(record: SalesRecord): Promise<void>;
    createInvoice(invoice: Invoice): Promise<bigint>;
    getAllExpenditures(): Promise<Array<Expenditure>>;
    getAllSalesRecords(): Promise<Array<SalesRecord>>;
    getInventory(): Promise<Array<InventoryItem>>;
    getInvoice(invoiceNumber: bigint): Promise<Invoice>;
    getSalesRecord(date: string): Promise<SalesRecord>;
    getStockMovements(plantName: string): Promise<Array<StockMovement>>;
    updateStockMovement(plantName: string, movement: StockMovement): Promise<void>;
}
import type { Expenditure as _Expenditure, ExpenditureCategory as _ExpenditureCategory, Invoice as _Invoice, MovementReason as _MovementReason, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, SaleItem as _SaleItem, SalesRecord as _SalesRecord, StockMovement as _StockMovement } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExpenditure(arg0: Expenditure): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenditure(to_candid_Expenditure_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenditure(to_candid_Expenditure_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0);
            return result;
        }
    }
    async addSalesRecord(arg0: SalesRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesRecord(to_candid_SalesRecord_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesRecord(to_candid_SalesRecord_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_Invoice_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_Invoice_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllExpenditures(): Promise<Array<Expenditure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenditures();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenditures();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSalesRecords(): Promise<Array<SalesRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalesRecords();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalesRecords();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventory(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_Invoice_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_Invoice_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesRecord(arg0: string): Promise<SalesRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesRecord(arg0);
                return from_candid_SalesRecord_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesRecord(arg0);
            return from_candid_SalesRecord_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockMovements(arg0: string): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockMovements(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockMovements(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStockMovement(arg0: string, arg1: StockMovement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStockMovement(arg0, to_candid_StockMovement_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStockMovement(arg0, to_candid_StockMovement_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ExpenditureCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenditureCategory): ExpenditureCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Expenditure_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expenditure): Expenditure {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MovementReason_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MovementReason): MovementReason {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SalesRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesRecord): SalesRecord {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StockMovement_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockMovement): StockMovement {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    description: string;
    category: _ExpenditureCategory;
    amount: bigint;
}): {
    date: string;
    description: string;
    category: ExpenditureCategory;
    amount: bigint;
} {
    return {
        date: value.date,
        description: value.description,
        category: from_candid_ExpenditureCategory_n16(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: [] | [string];
    paymentMethod: _PaymentMethod;
    customerPhoto: [] | [string];
    date: string;
    customerMobile: [] | [string];
    totalAmount: bigint;
    items: Array<_SaleItem>;
}): {
    customerName?: string;
    paymentMethod: PaymentMethod;
    customerPhoto?: string;
    date: string;
    customerMobile?: string;
    totalAmount: bigint;
    items: Array<SaleItem>;
} {
    return {
        customerName: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.customerName)),
        paymentMethod: from_candid_PaymentMethod_n22(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhoto: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.customerPhoto)),
        date: value.date,
        customerMobile: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.customerMobile)),
        totalAmount: value.totalAmount,
        items: value.items
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tax: bigint;
    customerName: string;
    lineItems: Array<_SaleItem>;
    paymentStatus: _PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
}): {
    tax: bigint;
    customerName: string;
    lineItems: Array<SaleItem>;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
} {
    return {
        tax: value.tax,
        customerName: value.customerName,
        lineItems: value.lineItems,
        paymentStatus: from_candid_PaymentStatus_n26(_uploadFile, _downloadFile, value.paymentStatus),
        customerPhone: value.customerPhone,
        date: value.date,
        grandTotal: value.grandTotal,
        invoiceNumber: value.invoiceNumber,
        discount: value.discount,
        subtotal: value.subtotal
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    notes: string;
    quantity: bigint;
    reason: _MovementReason;
}): {
    date: string;
    notes: string;
    quantity: bigint;
    reason: MovementReason;
} {
    return {
        date: value.date,
        notes: value.notes,
        quantity: value.quantity,
        reason: from_candid_MovementReason_n31(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    supplies: null;
} | {
    labour: null;
} | {
    rent: null;
} | {
    transport: null;
} | {
    utilities: null;
}): ExpenditureCategory {
    return "other" in value ? ExpenditureCategory.other : "supplies" in value ? ExpenditureCategory.supplies : "labour" in value ? ExpenditureCategory.labour : "rent" in value ? ExpenditureCategory.rent : "transport" in value ? ExpenditureCategory.transport : "utilities" in value ? ExpenditureCategory.utilities : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "card" in value ? PaymentMethod.card : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
}): PaymentStatus {
    return "paid" in value ? PaymentStatus.paid : "unpaid" in value ? PaymentStatus.unpaid : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adjustment: null;
} | {
    loss: null;
} | {
    sale: null;
} | {
    purchase: null;
}): MovementReason {
    return "adjustment" in value ? MovementReason.adjustment : "loss" in value ? MovementReason.loss : "sale" in value ? MovementReason.sale : "purchase" in value ? MovementReason.purchase : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expenditure>): Array<Expenditure> {
    return value.map((x)=>from_candid_Expenditure_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesRecord>): Array<SalesRecord> {
    return value.map((x)=>from_candid_SalesRecord_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockMovement>): Array<StockMovement> {
    return value.map((x)=>from_candid_StockMovement_n29(_uploadFile, _downloadFile, x));
}
function to_candid_ExpenditureCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenditureCategory): _ExpenditureCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Expenditure_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expenditure): _Expenditure {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_MovementReason_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementReason): _MovementReason {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SalesRecord_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesRecord): _SalesRecord {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_StockMovement_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockMovement): _StockMovement {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tax: bigint;
    customerName: string;
    lineItems: Array<SaleItem>;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
}): {
    tax: bigint;
    customerName: string;
    lineItems: Array<_SaleItem>;
    paymentStatus: _PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
} {
    return {
        tax: value.tax,
        customerName: value.customerName,
        lineItems: value.lineItems,
        paymentStatus: to_candid_PaymentStatus_n11(_uploadFile, _downloadFile, value.paymentStatus),
        customerPhone: value.customerPhone,
        date: value.date,
        grandTotal: value.grandTotal,
        invoiceNumber: value.invoiceNumber,
        discount: value.discount,
        subtotal: value.subtotal
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    description: string;
    category: ExpenditureCategory;
    amount: bigint;
}): {
    date: string;
    description: string;
    category: _ExpenditureCategory;
    amount: bigint;
} {
    return {
        date: value.date,
        description: value.description,
        category: to_candid_ExpenditureCategory_n3(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    notes: string;
    quantity: bigint;
    reason: MovementReason;
}): {
    date: string;
    notes: string;
    quantity: bigint;
    reason: _MovementReason;
} {
    return {
        date: value.date,
        notes: value.notes,
        quantity: value.quantity,
        reason: to_candid_MovementReason_n35(_uploadFile, _downloadFile, value.reason)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName?: string;
    paymentMethod: PaymentMethod;
    customerPhoto?: string;
    date: string;
    customerMobile?: string;
    totalAmount: bigint;
    items: Array<SaleItem>;
}): {
    customerName: [] | [string];
    paymentMethod: _PaymentMethod;
    customerPhoto: [] | [string];
    date: string;
    customerMobile: [] | [string];
    totalAmount: bigint;
    items: Array<_SaleItem>;
} {
    return {
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        paymentMethod: to_candid_PaymentMethod_n7(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhoto: value.customerPhoto ? candid_some(value.customerPhoto) : candid_none(),
        date: value.date,
        customerMobile: value.customerMobile ? candid_some(value.customerMobile) : candid_none(),
        totalAmount: value.totalAmount,
        items: value.items
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    paid: null;
} | {
    unpaid: null;
} {
    return value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.unpaid ? {
        unpaid: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementReason): {
    adjustment: null;
} | {
    loss: null;
} | {
    sale: null;
} | {
    purchase: null;
} {
    return value == MovementReason.adjustment ? {
        adjustment: null
    } : value == MovementReason.loss ? {
        loss: null
    } : value == MovementReason.sale ? {
        sale: null
    } : value == MovementReason.purchase ? {
        purchase: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenditureCategory): {
    other: null;
} | {
    supplies: null;
} | {
    labour: null;
} | {
    rent: null;
} | {
    transport: null;
} | {
    utilities: null;
} {
    return value == ExpenditureCategory.other ? {
        other: null
    } : value == ExpenditureCategory.supplies ? {
        supplies: null
    } : value == ExpenditureCategory.labour ? {
        labour: null
    } : value == ExpenditureCategory.rent ? {
        rent: null
    } : value == ExpenditureCategory.transport ? {
        transport: null
    } : value == ExpenditureCategory.utilities ? {
        utilities: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
