/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExpenditureCategory = IDL.Variant({
  'other' : IDL.Null,
  'supplies' : IDL.Null,
  'labour' : IDL.Null,
  'rent' : IDL.Null,
  'transport' : IDL.Null,
  'utilities' : IDL.Null,
});
export const Expenditure = IDL.Record({
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : ExpenditureCategory,
  'amount' : IDL.Nat,
});
export const InventoryItem = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'plantName' : IDL.Text,
  'unit' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'category' : IDL.Text,
  'costPrice' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const SaleItem = IDL.Record({
  'plantName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const SalesRecord = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'customerPhoto' : IDL.Opt(IDL.Text),
  'date' : IDL.Text,
  'customerMobile' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(SaleItem),
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const Invoice = IDL.Record({
  'tax' : IDL.Nat,
  'customerName' : IDL.Text,
  'lineItems' : IDL.Vec(SaleItem),
  'paymentStatus' : PaymentStatus,
  'customerPhone' : IDL.Text,
  'date' : IDL.Text,
  'grandTotal' : IDL.Nat,
  'invoiceNumber' : IDL.Nat,
  'discount' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const MovementReason = IDL.Variant({
  'adjustment' : IDL.Null,
  'loss' : IDL.Null,
  'sale' : IDL.Null,
  'purchase' : IDL.Null,
});
export const StockMovement = IDL.Record({
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'reason' : MovementReason,
});

export const idlService = IDL.Service({
  'addExpenditure' : IDL.Func([Expenditure], [], []),
  'addInventoryItem' : IDL.Func([InventoryItem], [], []),
  'addSalesRecord' : IDL.Func([SalesRecord], [], []),
  'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
  'getAllExpenditures' : IDL.Func([], [IDL.Vec(Expenditure)], ['query']),
  'getAllSalesRecords' : IDL.Func([], [IDL.Vec(SalesRecord)], ['query']),
  'getInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getSalesRecord' : IDL.Func([IDL.Text], [SalesRecord], ['query']),
  'getStockMovements' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StockMovement)],
      ['query'],
    ),
  'updateStockMovement' : IDL.Func([IDL.Text, StockMovement], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExpenditureCategory = IDL.Variant({
    'other' : IDL.Null,
    'supplies' : IDL.Null,
    'labour' : IDL.Null,
    'rent' : IDL.Null,
    'transport' : IDL.Null,
    'utilities' : IDL.Null,
  });
  const Expenditure = IDL.Record({
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : ExpenditureCategory,
    'amount' : IDL.Nat,
  });
  const InventoryItem = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'plantName' : IDL.Text,
    'unit' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'category' : IDL.Text,
    'costPrice' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
  });
  const SaleItem = IDL.Record({
    'plantName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const SalesRecord = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'customerPhoto' : IDL.Opt(IDL.Text),
    'date' : IDL.Text,
    'customerMobile' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(SaleItem),
  });
  const PaymentStatus = IDL.Variant({ 'paid' : IDL.Null, 'unpaid' : IDL.Null });
  const Invoice = IDL.Record({
    'tax' : IDL.Nat,
    'customerName' : IDL.Text,
    'lineItems' : IDL.Vec(SaleItem),
    'paymentStatus' : PaymentStatus,
    'customerPhone' : IDL.Text,
    'date' : IDL.Text,
    'grandTotal' : IDL.Nat,
    'invoiceNumber' : IDL.Nat,
    'discount' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const MovementReason = IDL.Variant({
    'adjustment' : IDL.Null,
    'loss' : IDL.Null,
    'sale' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const StockMovement = IDL.Record({
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'reason' : MovementReason,
  });
  
  return IDL.Service({
    'addExpenditure' : IDL.Func([Expenditure], [], []),
    'addInventoryItem' : IDL.Func([InventoryItem], [], []),
    'addSalesRecord' : IDL.Func([SalesRecord], [], []),
    'createInvoice' : IDL.Func([Invoice], [IDL.Nat], []),
    'getAllExpenditures' : IDL.Func([], [IDL.Vec(Expenditure)], ['query']),
    'getAllSalesRecords' : IDL.Func([], [IDL.Vec(SalesRecord)], ['query']),
    'getInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getSalesRecord' : IDL.Func([IDL.Text], [SalesRecord], ['query']),
    'getStockMovements' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StockMovement)],
        ['query'],
      ),
    'updateStockMovement' : IDL.Func([IDL.Text, StockMovement], [], []),
  });
};

export const init = ({ IDL }) => { return []; };