/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expenditure {
  'date' : string,
  'description' : string,
  'category' : ExpenditureCategory,
  'amount' : bigint,
}
export type ExpenditureCategory = { 'other' : null } |
  { 'supplies' : null } |
  { 'labour' : null } |
  { 'rent' : null } |
  { 'transport' : null } |
  { 'utilities' : null };
export interface InventoryItem {
  'stockQuantity' : bigint,
  'plantName' : string,
  'unit' : string,
  'sellingPrice' : bigint,
  'category' : string,
  'costPrice' : bigint,
}
export interface Invoice {
  'tax' : bigint,
  'customerName' : string,
  'lineItems' : Array<SaleItem>,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : string,
  'date' : string,
  'grandTotal' : bigint,
  'invoiceNumber' : bigint,
  'discount' : bigint,
  'subtotal' : bigint,
}
export type MovementReason = { 'adjustment' : null } |
  { 'loss' : null } |
  { 'sale' : null } |
  { 'purchase' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'card' : null } |
  { 'cash' : null };
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null };
export interface SaleItem {
  'plantName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface SalesRecord {
  'customerName' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'customerPhoto' : [] | [string],
  'date' : string,
  'customerMobile' : [] | [string],
  'totalAmount' : bigint,
  'items' : Array<SaleItem>,
}
export interface StockMovement {
  'date' : string,
  'notes' : string,
  'quantity' : bigint,
  'reason' : MovementReason,
}
export interface _SERVICE {
  'addExpenditure' : ActorMethod<[Expenditure], undefined>,
  'addInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'addSalesRecord' : ActorMethod<[SalesRecord], undefined>,
  'createInvoice' : ActorMethod<[Invoice], bigint>,
  'getAllExpenditures' : ActorMethod<[], Array<Expenditure>>,
  'getAllSalesRecords' : ActorMethod<[], Array<SalesRecord>>,
  'getInventory' : ActorMethod<[], Array<InventoryItem>>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getSalesRecord' : ActorMethod<[string], SalesRecord>,
  'getStockMovements' : ActorMethod<[string], Array<StockMovement>>,
  'updateStockMovement' : ActorMethod<[string, StockMovement], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];