/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SalesRecord {
    customerName?: string;
    paymentMethod: PaymentMethod;
    customerPhoto?: string;
    date: string;
    customerMobile?: string;
    totalAmount: bigint;
    items: Array<SaleItem>;
    billingNumber: string;
}
export interface Invoice {
    tax: bigint;
    customerName: string;
    lineItems: Array<SaleItem>;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
}
export interface Expenditure {
    date: string;
    description: string;
    category: ExpenditureCategory;
    amount: bigint;
}
export interface InventoryItem {
    plantName: string;
    unit: string;
    sellingPrice: bigint;
    category: string;
    currentStock: bigint;
    costPrice: bigint;
}
export interface PriorityRequestCreate {
    customerName: string;
    status: PriorityRequestStatus;
    plantName: string;
    customerPhone: string;
    plantVariety: string;
    deliveryDate?: string;
    notes?: string;
    quantity: bigint;
    requestDate: string;
    wantedDate: string;
}
export interface PriorityRequest {
    id: bigint;
    customerName: string;
    status: PriorityRequestStatus;
    plantName: string;
    customerPhone: string;
    plantVariety: string;
    deliveryDate?: string;
    notes?: string;
    quantity: bigint;
    requestDate: string;
    wantedDate: string;
}
export interface StockMovement {
    date: string;
    notes: string;
    quantity: bigint;
    reason: MovementReason;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface SaleItem {
    plantName: string;
    quantity: bigint;
    unitPrice: bigint;
}
export enum ExpenditureCategory {
    other = "other",
    supplies = "supplies",
    labour = "labour",
    rent = "rent",
    transport = "transport",
    utilities = "utilities"
}
export enum MovementReason {
    adjustment = "adjustment",
    loss = "loss",
    sale = "sale",
    purchase = "purchase"
}
export enum PaymentMethod {
    upi = "upi",
    card = "card",
    cash = "cash"
}
export enum PaymentStatus {
    paid = "paid",
    unpaid = "unpaid"
}
export enum PriorityRequestStatus {
    pending = "pending",
    fulfilled = "fulfilled"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addExpenditure(exp: Expenditure): Promise<void>;
    addInventoryItem(item: InventoryItem): Promise<void>;
    addPriorityRequest(request: PriorityRequestCreate): Promise<bigint>;
    addSale(sale: SalesRecord): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(user: Principal, role: UserRole): Promise<void>;
    createInvoice(invoice: Invoice): Promise<bigint>;
    deleteInventoryItem(plantName: string): Promise<void>;
    deleteSale(billingNumber: string): Promise<void>;
    getAllExpenditures(): Promise<Array<Expenditure>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInventory(): Promise<Array<InventoryItem>>;
    getInvoice(invoiceNumber: bigint): Promise<Invoice>;
    getMyRole(): Promise<UserRole>;
    getPriorityRequests(): Promise<Array<PriorityRequest>>;
    getSales(): Promise<Array<SalesRecord>>;
    getSalesByPlant(plantName: string, startDate: string, endDate: string): Promise<[bigint, bigint]>;
    getStockMovements(plantName: string): Promise<Array<StockMovement>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordStockMovement(plantName: string, movement: StockMovement): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateInventoryItem(plantName: string, updatedItem: InventoryItem): Promise<void>;
    updatePriorityRequestStatus(id: bigint, status: PriorityRequestStatus, deliveryDate: string | null): Promise<void>;
}
import type { Expenditure as _Expenditure, ExpenditureCategory as _ExpenditureCategory, Invoice as _Invoice, MovementReason as _MovementReason, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, PriorityRequest as _PriorityRequest, PriorityRequestCreate as _PriorityRequestCreate, PriorityRequestStatus as _PriorityRequestStatus, SaleItem as _SaleItem, SalesRecord as _SalesRecord, StockMovement as _StockMovement, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addExpenditure(arg0: Expenditure): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpenditure(to_candid_Expenditure_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpenditure(to_candid_Expenditure_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0);
            return result;
        }
    }
    async addPriorityRequest(arg0: PriorityRequestCreate): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPriorityRequest(to_candid_PriorityRequestCreate_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPriorityRequest(to_candid_PriorityRequestCreate_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSale(arg0: SalesRecord): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(to_candid_SalesRecord_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(to_candid_SalesRecord_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createInvoice(arg0: Invoice): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_Invoice_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_Invoice_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteInventoryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteSale(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSale(arg0);
            return result;
        }
    }
    async getAllExpenditures(): Promise<Array<Expenditure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenditures();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenditures();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventory(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_Invoice_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_Invoice_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriorityRequests(): Promise<Array<PriorityRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriorityRequests();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriorityRequests();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSales(): Promise<Array<SalesRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesByPlant(arg0: string, arg1: string, arg2: string): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesByPlant(arg0, arg1, arg2);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesByPlant(arg0, arg1, arg2);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getStockMovements(arg0: string): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockMovements(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockMovements(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordStockMovement(arg0: string, arg1: StockMovement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordStockMovement(arg0, to_candid_StockMovement_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordStockMovement(arg0, to_candid_StockMovement_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateInventoryItem(arg0: string, arg1: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, arg1);
            return result;
        }
    }
    async updatePriorityRequestStatus(arg0: bigint, arg1: PriorityRequestStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePriorityRequestStatus(arg0, to_candid_PriorityRequestStatus_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n51(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePriorityRequestStatus(arg0, to_candid_PriorityRequestStatus_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n51(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ExpenditureCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenditureCategory): ExpenditureCategory {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Expenditure_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expenditure): Expenditure {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MovementReason_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MovementReason): MovementReason {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PriorityRequestStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriorityRequestStatus): PriorityRequestStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PriorityRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriorityRequest): PriorityRequest {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_SalesRecord_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesRecord): SalesRecord {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_StockMovement_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockMovement): StockMovement {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    description: string;
    category: _ExpenditureCategory;
    amount: bigint;
}): {
    date: string;
    description: string;
    category: ExpenditureCategory;
    amount: bigint;
} {
    return {
        date: value.date,
        description: value.description,
        category: from_candid_ExpenditureCategory_n22(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tax: bigint;
    customerName: string;
    lineItems: Array<_SaleItem>;
    paymentStatus: _PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
}): {
    tax: bigint;
    customerName: string;
    lineItems: Array<SaleItem>;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
} {
    return {
        tax: value.tax,
        customerName: value.customerName,
        lineItems: value.lineItems,
        paymentStatus: from_candid_PaymentStatus_n29(_uploadFile, _downloadFile, value.paymentStatus),
        customerPhone: value.customerPhone,
        date: value.date,
        grandTotal: value.grandTotal,
        invoiceNumber: value.invoiceNumber,
        discount: value.discount,
        subtotal: value.subtotal
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _PriorityRequestStatus;
    plantName: string;
    customerPhone: string;
    plantVariety: string;
    deliveryDate: [] | [string];
    notes: [] | [string];
    quantity: bigint;
    requestDate: string;
    wantedDate: string;
}): {
    id: bigint;
    customerName: string;
    status: PriorityRequestStatus;
    plantName: string;
    customerPhone: string;
    plantVariety: string;
    deliveryDate?: string;
    notes?: string;
    quantity: bigint;
    requestDate: string;
    wantedDate: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_PriorityRequestStatus_n34(_uploadFile, _downloadFile, value.status),
        plantName: value.plantName,
        customerPhone: value.customerPhone,
        plantVariety: value.plantVariety,
        deliveryDate: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.deliveryDate)),
        notes: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity,
        requestDate: value.requestDate,
        wantedDate: value.wantedDate
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: [] | [string];
    paymentMethod: _PaymentMethod;
    customerPhoto: [] | [string];
    date: string;
    customerMobile: [] | [string];
    totalAmount: bigint;
    items: Array<_SaleItem>;
    billingNumber: string;
}): {
    customerName?: string;
    paymentMethod: PaymentMethod;
    customerPhoto?: string;
    date: string;
    customerMobile?: string;
    totalAmount: bigint;
    items: Array<SaleItem>;
    billingNumber: string;
} {
    return {
        customerName: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.customerName)),
        paymentMethod: from_candid_PaymentMethod_n40(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhoto: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.customerPhoto)),
        date: value.date,
        customerMobile: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.customerMobile)),
        totalAmount: value.totalAmount,
        items: value.items,
        billingNumber: value.billingNumber
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    notes: string;
    quantity: bigint;
    reason: _MovementReason;
}): {
    date: string;
    notes: string;
    quantity: bigint;
    reason: MovementReason;
} {
    return {
        date: value.date,
        notes: value.notes,
        quantity: value.quantity,
        reason: from_candid_MovementReason_n45(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    supplies: null;
} | {
    labour: null;
} | {
    rent: null;
} | {
    transport: null;
} | {
    utilities: null;
}): ExpenditureCategory {
    return "other" in value ? ExpenditureCategory.other : "supplies" in value ? ExpenditureCategory.supplies : "labour" in value ? ExpenditureCategory.labour : "rent" in value ? ExpenditureCategory.rent : "transport" in value ? ExpenditureCategory.transport : "utilities" in value ? ExpenditureCategory.utilities : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
}): PaymentStatus {
    return "paid" in value ? PaymentStatus.paid : "unpaid" in value ? PaymentStatus.unpaid : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    fulfilled: null;
}): PriorityRequestStatus {
    return "pending" in value ? PriorityRequestStatus.pending : "fulfilled" in value ? PriorityRequestStatus.fulfilled : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "card" in value ? PaymentMethod.card : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adjustment: null;
} | {
    loss: null;
} | {
    sale: null;
} | {
    purchase: null;
}): MovementReason {
    return "adjustment" in value ? MovementReason.adjustment : "loss" in value ? MovementReason.loss : "sale" in value ? MovementReason.sale : "purchase" in value ? MovementReason.purchase : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expenditure>): Array<Expenditure> {
    return value.map((x)=>from_candid_Expenditure_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriorityRequest>): Array<PriorityRequest> {
    return value.map((x)=>from_candid_PriorityRequest_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesRecord>): Array<SalesRecord> {
    return value.map((x)=>from_candid_SalesRecord_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockMovement>): Array<StockMovement> {
    return value.map((x)=>from_candid_StockMovement_n43(_uploadFile, _downloadFile, x));
}
function to_candid_ExpenditureCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenditureCategory): _ExpenditureCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Expenditure_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expenditure): _Expenditure {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_MovementReason_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementReason): _MovementReason {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PriorityRequestCreate_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriorityRequestCreate): _PriorityRequestCreate {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PriorityRequestStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriorityRequestStatus): _PriorityRequestStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SalesRecord_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesRecord): _SalesRecord {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_StockMovement_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockMovement): _StockMovement {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName?: string;
    paymentMethod: PaymentMethod;
    customerPhoto?: string;
    date: string;
    customerMobile?: string;
    totalAmount: bigint;
    items: Array<SaleItem>;
    billingNumber: string;
}): {
    customerName: [] | [string];
    paymentMethod: _PaymentMethod;
    customerPhoto: [] | [string];
    date: string;
    customerMobile: [] | [string];
    totalAmount: bigint;
    items: Array<_SaleItem>;
    billingNumber: string;
} {
    return {
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        paymentMethod: to_candid_PaymentMethod_n11(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhoto: value.customerPhoto ? candid_some(value.customerPhoto) : candid_none(),
        date: value.date,
        customerMobile: value.customerMobile ? candid_some(value.customerMobile) : candid_none(),
        totalAmount: value.totalAmount,
        items: value.items,
        billingNumber: value.billingNumber
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tax: bigint;
    customerName: string;
    lineItems: Array<SaleItem>;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
}): {
    tax: bigint;
    customerName: string;
    lineItems: Array<_SaleItem>;
    paymentStatus: _PaymentStatus;
    customerPhone: string;
    date: string;
    grandTotal: bigint;
    invoiceNumber: bigint;
    discount: bigint;
    subtotal: bigint;
} {
    return {
        tax: value.tax,
        customerName: value.customerName,
        lineItems: value.lineItems,
        paymentStatus: to_candid_PaymentStatus_n17(_uploadFile, _downloadFile, value.paymentStatus),
        customerPhone: value.customerPhone,
        date: value.date,
        grandTotal: value.grandTotal,
        invoiceNumber: value.invoiceNumber,
        discount: value.discount,
        subtotal: value.subtotal
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    description: string;
    category: ExpenditureCategory;
    amount: bigint;
}): {
    date: string;
    description: string;
    category: _ExpenditureCategory;
    amount: bigint;
} {
    return {
        date: value.date,
        description: value.description,
        category: to_candid_ExpenditureCategory_n3(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    notes: string;
    quantity: bigint;
    reason: MovementReason;
}): {
    date: string;
    notes: string;
    quantity: bigint;
    reason: _MovementReason;
} {
    return {
        date: value.date,
        notes: value.notes,
        quantity: value.quantity,
        reason: to_candid_MovementReason_n49(_uploadFile, _downloadFile, value.reason)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: PriorityRequestStatus;
    plantName: string;
    customerPhone: string;
    plantVariety: string;
    deliveryDate?: string;
    notes?: string;
    quantity: bigint;
    requestDate: string;
    wantedDate: string;
}): {
    customerName: string;
    status: _PriorityRequestStatus;
    plantName: string;
    customerPhone: string;
    plantVariety: string;
    deliveryDate: [] | [string];
    notes: [] | [string];
    quantity: bigint;
    requestDate: string;
    wantedDate: string;
} {
    return {
        customerName: value.customerName,
        status: to_candid_PriorityRequestStatus_n7(_uploadFile, _downloadFile, value.status),
        plantName: value.plantName,
        customerPhone: value.customerPhone,
        plantVariety: value.plantVariety,
        deliveryDate: value.deliveryDate ? candid_some(value.deliveryDate) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        quantity: value.quantity,
        requestDate: value.requestDate,
        wantedDate: value.wantedDate
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    paid: null;
} | {
    unpaid: null;
} {
    return value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.unpaid ? {
        unpaid: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenditureCategory): {
    other: null;
} | {
    supplies: null;
} | {
    labour: null;
} | {
    rent: null;
} | {
    transport: null;
} | {
    utilities: null;
} {
    return value == ExpenditureCategory.other ? {
        other: null
    } : value == ExpenditureCategory.supplies ? {
        supplies: null
    } : value == ExpenditureCategory.labour ? {
        labour: null
    } : value == ExpenditureCategory.rent ? {
        rent: null
    } : value == ExpenditureCategory.transport ? {
        transport: null
    } : value == ExpenditureCategory.utilities ? {
        utilities: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementReason): {
    adjustment: null;
} | {
    loss: null;
} | {
    sale: null;
} | {
    purchase: null;
} {
    return value == MovementReason.adjustment ? {
        adjustment: null
    } : value == MovementReason.loss ? {
        loss: null
    } : value == MovementReason.sale ? {
        sale: null
    } : value == MovementReason.purchase ? {
        purchase: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriorityRequestStatus): {
    pending: null;
} | {
    fulfilled: null;
} {
    return value == PriorityRequestStatus.pending ? {
        pending: null
    } : value == PriorityRequestStatus.fulfilled ? {
        fulfilled: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
